- Association: IEEE Symposium on Security and Privacy (IEEE S&P)
  Job: External Reviewer
  Time: 2025

- Association: ACM SIGSAC Conference on Computer and Communications Security (CCS)
  Job: External Reviewer
  Time: 2024, 2022

- Association: Tsinghua Science and Technology (TST)
  Job: Reviewer
  Time: 2025, 2024

- Association: IEEE Transactions on Dependable and Secure Computing (TDSC)
  Job: Reviewer
  Time: 2023
