- Association: ACM SIGSAC Conference on Computer and Communications Security (CCS)
  Job: Program Committee Member
  Time: 2026
  
- Association: IEEE Symposium on Security and Privacy (IEEE S&P)
  Job: Program Committee Member
  Time: 2026

- Association: ACM Workshop on Artificial Intelligence and Security (AISec, co-located with CCS)
  Job: Program Committee Member
  Time: 2025

- Association: Workshop on Rethinking Malware Analysis (WoRMA, co-located with IEEE EuroS&P)
  Job: Program Committee Member
  Time: 2025

# - Association: USENIX Security Symposium (USENIX Security)
#   Job: External Reviewer
#   Time: 2025

# - Association: IEEE Symposium on Security and Privacy (IEEE S&P)
#   Job: External Reviewer
#   Time: 2025

- Association: ACM SIGSAC Conference on Computer and Communications Security (CCS), <br>IEEE Symposium on Security and Privacy (IEEE S&P)*, USENIX Security Symposium (USENIX Security)*
  Job: External Reviewer
  Time: 2022, 2024, <br>2025*(2)

# - Association: ACM Transactions on Privacy and Security (TOPS)
#   Job: Reviewer
#   Time: 2025

# - Association: Tsinghua Science and Technology (TST)
#   Job: Reviewer
#   Time: 2025, 2024

# - Association: IEEE Transactions on Circuits and Systems for Video Technology (TCSVT)
#   Job: Reviewer
#   Time: 2024

- Association: IEEE Transactions on Dependable and Secure Computing (TDSC), ACM Transactions on Privacy and Security (TOPS), IEEE Transactions on Circuits and Systems for Video Technology (TCSVT), Tsinghua Science and Technology (TST)
  Job: Journal Reviewer
  Time: 2023~
